INSERT INTO MED_PACIENTES (NOMBRE, RUT, EDAD, HABITACION, DIAGNOSTICO, ESTADO, ACTIVO)
VALUES ('Valentina Rojas', '18.245.991-2', 56, 'UCI-01', 'Sepsis respiratoria', 'CRITICO', 1);

INSERT INTO MED_PACIENTES (NOMBRE, RUT, EDAD, HABITACION, DIAGNOSTICO, ESTADO, ACTIVO)
VALUES ('Hector Munoz', '12.884.221-8', 68, 'UCI-02', 'Postoperatorio cardiaco', 'OBSERVACION', 1);

INSERT INTO MED_PACIENTES (NOMBRE, RUT, EDAD, HABITACION, DIAGNOSTICO, ESTADO, ACTIVO)
VALUES ('Camila Araya', '20.117.456-1', 34, 'UCI-03', 'Trauma toracico', 'CRITICO', 1);

INSERT INTO MED_PACIENTES (NOMBRE, RUT, EDAD, HABITACION, DIAGNOSTICO, ESTADO, ACTIVO)
VALUES ('Marcelo Soto', '9.887.110-5', 73, 'UCI-04', 'Insuficiencia cardiaca', 'ESTABLE', 1);

COMMIT;
